### ISSUE TITLE
Move away from "last 2 versions"

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/create-react-app#48]
Now considered harmful (at least by some).

See, for example, https://jamie.build/last-2-versions

**Comment by asbjornh** [comment]
This should go for both .babelrc and browserslist then. Do we realt need both BTW?

**Comment by asbjornh** [comment]
From Babel preset env docs:

> Browserslist Integration

> For browser- or Electron-based projects, we recommend using a .browserslistrc file to specify targets. You may already have this configuration file as it is used by many tools in the ecosystem, like autoprefixer, stylelint, eslint-plugin-compat and many others.

> By default @babel/preset-env will use browserslist config sources unless either the targets or ignoreBrowserslistConfig options are set.

While we’re at it we should probably remove the targets config in babelrc and update the browserslist config file to avoid having two sources of truth
