### ISSUE TITLE
CSS isn't minified when building for production

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/create-react-app#54]
It seems like support for minification using `css-loader` was dropped in `1.0.0` ([changelog](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#100-2018-07-06)).
The scaffolded project uses `^1.0.0` and still uses the `minimize` option. I suspect we might have a few sites in production with un-minified css 😄 (I can confirm at least one).

The solution is also described in the [changelog](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#100-2018-07-06)

**Comment by pellebjerkestrand** [comment]
I'll start work on this.
