### ISSUE TITLE
Fix prettier end of line issue on windows

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/create-react-app#61]
With the currently scaffolded config, prettier `>=1.15.0` will gernerate warnings for all lines of javascript when using source control and running webpack on windows. To fix this, set `"endOfLine": "auto"` in the prettier config in `.eslintrc.json`

**Comment by Lkleven** [comment]
fixed by https://github.com/Creuna-Oslo/create-react-app/pull/62
